### ISSUE TITLE
Sniffer not working on rev C boards.

### ISSUE THREAD

**Issue by matlo** [matlo/bb_usb_sniffer#1]
I was told the sniffer does not work on rev C boards.
The sniffer does not work because the kernel does not power up the USB hub.
The following kernel patches have to be applied:
https://github.com/Angstrom-distribution/meta-ti/tree/master/recipes-kernel/linux/linux-omap-psp-2.6.32/beagleboard-xmc

**Comment by mrmmarcell** [comment]
@enarik You ever got that to work?
