### ISSUE TITLE
Original beagleboard-usbsniffer-kernel repository is unavailable

### ISSUE THREAD

**Issue by kelleyk** [matlo/bb_usb_sniffer#2]
The build instructions for this project require access to the original Google Summer of Code project's repository.  Gitorious, where the original project's repository was hosted, has been offline for quite a while now; the Internet Archive apparently intends to host a read-only copy of it eventually, but I haven't seen an ETA mentioned.

Is there any chance that you have a clone of that repository hanging out that you could make available?  I would love to experiment with your project!

**Comment by matlo** [comment]
I pushed it here: https://github.com/matlo/beagleboard-usbsniffer-kernel
I also updated the instructions.
Let me know if you need anything else.

**Comment by kelleyk** [comment]
Thank you!
