### ISSUE TITLE
Link not working

### ISSUE THREAD

**Issue by mrmmarcell** [matlo/bb_usb_sniffer#3]
Hi, sorry to bother, could you please upload the image again? Link is down.
http://gimx.fr/download/bb_sniffer_small.img.7z

**Comment by matlo** [comment]
I just fixed the link. Your browser may keep using the old redirect. The link points to https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/diyps3controller/bb_sniffer_small.img.7z

**Comment by matlo** [comment]
If you are targeting HID devices or similar, you may be interested by this project: https://github.com/matlo/serialusb
